### PR TITLE
removed example

### PR DESCRIPTION
**Pull request by igniti0n**

### CODE REVIEW

**Comment by igniti0n** [comment]
I added repository implementation with methods and dependencies, as well as tests for that repository with methods and dependencies. 

It is not possible currently to use one brick inside another one. There is currenlty and open issue regarding using brick in other bricks: https://github.com/felangel/mason/issues/215

I removed the models. We can use the model brick for creating models, instead of the freezed package: https://brickhub.dev/bricks/model/0.3.7

Currently, we are using a state for each notifier. We can use this 'RequestProvider' to not have to write the same states for all the states of the notifiers, and not have to generate them with freezed: https://github.com/infinum/flutter-bits/tree/master/request_provider.

**Comment by DMesek** [comment]
Great! Would also be great to fork the model brick and ask the user in which feature they want to create a model/entity... that way we know exactly where to put that file in out folder structure :)

**Comment by DMesek** [comment]
Ohh and regarding the state, we are going to create our custom BaseNotifier and BaseState to match our needs

**Comment by igniti0n** [comment]
> Great! Would also be great to fork the model brick and ask the user in which feature they want to create a model/entity... that way we know exactly where to put that file in out folder structure :)

Good idea! I will later look into doing that.

**Pull request merged**
